name: Clang-format formatter

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run python auto formatting script
        shell: bash
        run: |
          python3 style.py
      
      - name: Add styled files to git commit
        shell: bash
        run: |
          git add src

      - name: Commit changed files
        shell: bash
        run: |
          git commit -m "Auto formatter run"

      - name: Push commit
        shell: bash
        run: |
          git push
