name: Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: test
        shell: bash
        run: |
          cd ..
          tree
        
      - name: Update apt
        shell: bash
        run: |
          sudo apt-get update

      - name: install g++
        shell: bash
        run: |
          sudo apt-get install g++

      - name: Test with catch2
        shell: bash
        run: |
          make clean
          make test
          ./test
