name: Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  MacOS_Test:

    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Test with catch2
        shell: bash
        run: |
          make clean
          make test
          ./test

  Ubuntu_Test:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Test with catch2
        shell: bash
        run: |
          make clean
          make test
          ./test