name: Unit Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: Update apt
        run: |
          sudo apt-get update
    steps:
      - name: install g++
        run: |
          sudo apt-get install g++

    steps:
      - name: Test with catch2
        run: |
          make clean
          make test
          ./test
